env:
    browser: true
    es2021: true
extends:
    - eslint:recommended
    - plugin:vue/essential
    - plugin:@typescript-eslint/recommended
    - prettier
    - plugin:prettier/recommended
parser: 'vue-eslint-parser'
parserOptions:
    ecmaVersion: latest
    parser: '@typescript-eslint/parser'
    sourceType: module
plugins:
    - vue
    - '@typescript-eslint'
    - 'prettier'
rules:
    prettier/prettier:
        - error
    indent:
        - error
        - 4
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
    semi:
        - error
        - never
    vue/no-multiple-template-root: off
    vue/multi-word-component-names: off
ignorePatterns:
    - '.eslintrc.js'
    - 'postcss.config.js'
    - 'tailwind.config.js'
    - '.commitlintrc.js'
    - '.stylelintrc.js'
